# Generated by Django 4.0.4 on 2022-08-29 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog/blog/default.PNG', upload_to='blog/blog/image', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
