# Generated by Django 4.0.4 on 2022-08-29 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.PNG', upload_to='development\\blog/image', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
