# Generated by Django 4.0.4 on 2022-09-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_blog_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
