# Generated by Django 4.0.4 on 2022-09-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_blog_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subtitle',
        ),
    ]
